apiVersion: v1
kind: Secret
metadata:
  name: {{ template "log-scraper.fullname" . }}
  labels:
    app: {{ template "log-scraper.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.service.newRelicAccountId }}
  nr-account-id: {{ .Values.service.newRelicAccountId | toString | b64enc | quote }}
  {{ else }}
  nr-account-id: {{ randNumeric 7 | toString | b64enc | quote }}
  {{ end }}
  {{ if .Values.service.newRelicApiKey }}
  nr-api-key:  {{ .Values.service.newRelicApiKey | toString | b64enc | quote }}
  {{ else }}
  nr-api-key: {{ randAlphaNum 10 | toString | b64enc | quote }}
  {{ end }}
